/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\Marwa\Downloads\basketball.glb --transform 
Files: C:\Users\Marwa\Downloads\basketball.glb [3.19MB] > C:\Users\Marwa\basketball-transformed.glb [355.43KB] (89%)
Author: 24fpsboy (https://sketchfab.com/ikagogava)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basketball-eb172b5f4e544f428c2bcd8d3f067a91
Title: Basketball
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/basketball-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.None} />
    </group>
  )
}

useGLTF.preload('/basketball-transformed.glb')
